import {useEffect,useState} from 'react';
import {api} from './api';
import type {Act,Command,Event,User} from './types';

type Account=User&{username:string;disabled:boolean};
const roles=['audience','judge','host','backstage','controller','event_admin','super_admin'];
const members=(value:FormDataEntryValue|null)=>String(value||'').split(';').map(s=>s.trim()).filter(Boolean);
function useTask(){const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');return{busy,message,error,async run(fn:()=>Promise<unknown>,success:string){setBusy(true);setError('');setMessage('');try{await fn();setMessage(success);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}}}
function Feedback({task}:{task:ReturnType<typeof useTask>}){return <>{task.error&&<p role="alert" className="error-text">{task.error}</p>}{task.message&&<p role="status" className="lime-text">{task.message}</p>}</>}

export function PasswordSettings({onChanged}:{onChanged:()=>Promise<void>}){const task=useTask();return <section className="panel"><div className="panel-head"><h2>Change your password</h2></div><form className="pad form-stack" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(f.get('new_password')!==f.get('repeat')){form.querySelector<HTMLInputElement>('[name=repeat]')?.setCustomValidity('Passwords must match.');form.reportValidity();return}if(await task.run(()=>api('/password',{old_password:f.get('old_password'),new_password:f.get('new_password')}),'Password changed. Sign in again with your new password.')){form.reset();await onChanged()}}}><p className="muted">Changing your password signs out every existing session.</p><label>Current password<input name="old_password" type="password" autoComplete="current-password" required/></label><label>New password<input name="new_password" type="password" minLength={12} autoComplete="new-password" required/></label><label>Repeat new password<input name="repeat" type="password" minLength={12} autoComplete="new-password" required onInput={e=>e.currentTarget.setCustomValidity('')}/></label><Feedback task={task}/><button className="primary" disabled={task.busy}>Change password</button></form></section>}

export function AccountTools({accounts,user,refresh}:{accounts:Account[];user:User;refresh:()=>Promise<unknown>}){const [selected,setSelected]=useState(''),[action,setAction]=useState('revoke_sessions');const task=useTask();const target=accounts.find(u=>String(u.id)===selected);return <section className="panel wide"><div className="panel-head"><h2>Manage account access</h2></div><form className="pad form-stack" onSubmit={async e=>{e.preventDefault();if(!target)return;const form=e.currentTarget;const f=new FormData(form);if(!confirm(`${action.replaceAll('_',' ')} for ${target.name}?`))return;if(await task.run(()=>api(`/users/${target.id}/manage`,{action,...(action==='reset_password'?{password:f.get('password')}:{}),...(action==='role'?{role:f.get('role')}:{})}),'Account updated.')){const input=form.querySelector<HTMLInputElement>('[name=password]');if(input)input.value='';await refresh()}}}><label>Account<select required value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose an account</option>{accounts.filter(a=>a.id!==user.id&&(user.role==='super_admin'||!['super_admin','event_admin'].includes(a.role))).map(a=><option key={a.id} value={a.id}>{a.name} · {a.username} · {a.disabled?'disabled':a.role}</option>)}</select></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="revoke_sessions">Sign out all sessions</option><option value="disable">Disable account</option><option value="enable">Enable account</option><option value="reset_password">Reset password</option><option value="role">Change role</option></select></label>{action==='reset_password'&&<label>New password<input name="password" type="password" minLength={12} required autoComplete="new-password"/></label>}{action==='role'&&<label>New role<select name="role">{roles.filter(r=>user.role==='super_admin'||!['event_admin','super_admin'].includes(r)).map(r=><option key={r}>{r}</option>)}</select></label>}<p className="muted">Disabling an account, resetting its password or changing its role also revokes its sessions. Replace assigned judges on the panel first.</p><Feedback task={task}/><button disabled={!target||task.busy}>Apply account change</button></form></section>}

export function RegistrationForm({event,user,refresh}:{event:Event;user:User|null;refresh:()=>Promise<void>}){const task=useTask();if(user?.role!=='audience')return null;if(event.my_registration)return <section className="panel pad"><h2>Your registration</h2><p>{event.my_registration.name} · {event.my_registration.state.toLowerCase()}</p><p className="muted">Contact backstage for changes to your submitted act.</p></section>;if(!event.registration_open)return null;return <section className="panel"><div className="panel-head"><h2>Bring your talent to the stage</h2></div><form className="pad form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await task.run(()=>api('/register',{name:f.get('name'),category:f.get('category'),bio:f.get('bio'),members:members(f.get('members')),consent:f.get('consent')==='on'}),'Registration sent for organiser approval.'))await refresh()}}><label>Stage or team name<input name="name" required maxLength={80}/></label><label>Talent category<input name="category" required maxLength={50}/></label><label>Team members (optional; separate with semicolons)<input name="members" maxLength={1000}/></label><label>Short host introduction<textarea name="bio" maxLength={500}/></label><label className="checkbox-row"><input name="consent" type="checkbox" required/>I and any listed team members agree to have these stage details and revealed scores displayed for this event.</label><Feedback task={task}/><button className="primary" disabled={task.busy}>Submit registration</button></form></section>}

export function RosterImport({command}:{command:Command}){const [raw,setRaw]=useState(''),[error,setError]=useState('');return <details className="panel pad"><summary>Import performers from CSV</summary><p className="muted">Headers: name,category,bio,members. Separate team members with semicolons. Duplicate stage names are rejected; the whole import succeeds or none of it is saved.</p><label>CSV file<input type="file" accept=".csv,text/csv" onChange={async e=>{setError('');const file=e.target.files?.[0];if(!file)return;if(file.size>100000){setError('Choose a CSV under 100 KB.');return}setRaw(await file.text())}}/></label><form className="form-stack spaced" onSubmit={async e=>{e.preventDefault();if(await command('roster_import',{csv:raw}))setRaw('')}}><label>Review CSV<textarea rows={5} value={raw} onChange={e=>setRaw(e.target.value)} required maxLength={100000}/></label>{error&&<p role="alert" className="error-text">{error}</p>}<button disabled={!raw} className="primary">Import roster</button></form></details>}

export function PerformerTools({act,user,command}:{act:Act;user:User;command:Command}){const [edit,setEdit]=useState(false),[reason,setReason]=useState('');const admin=['super_admin','event_admin'].includes(user.role);const canEdit=admin||user.role==='backstage';const waiting=!['ON_STAGE','PERFORMING','JUDGING','REVEAL','COMPLETED','VOID'].includes(act.state);return <div className="form-stack spaced">{act.members?.length?<p className="muted">Team: {act.members.join(', ')}</p>:null}{act.state==='PENDING'&&canEdit&&<button className="primary" onClick={()=>command('approve',{},act.id)}>Approve registration</button>}{canEdit&&waiting&&<button onClick={()=>setEdit(!edit)}>{edit?'Close editor':'Edit performer / team'}</button>}{edit&&canEdit&&waiting&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await command('participant_edit',{name:f.get('name'),category:f.get('category'),bio:f.get('bio'),members:members(f.get('members'))},act.id))setEdit(false)}}><label>Stage name<input name="name" defaultValue={act.name} required maxLength={80}/></label><label>Talent<input name="category" defaultValue={act.category} required maxLength={50}/></label><label>Team members (semicolon separated)<input name="members" defaultValue={act.members?.join('; ')||''} maxLength={1000}/></label><label>Introduction<textarea name="bio" defaultValue={act.bio} maxLength={500}/></label><button className="primary">Save performer</button></form>}{admin&&!['COMPLETED','REVEAL','VOID'].includes(act.state)&&<details><summary>Act recovery</summary><label className="spaced">Reason (recorded in the audit log)<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={300}/></label><div className="button-group spaced">{['ABSENT','SKIPPED'].includes(act.state)&&<button disabled={!reason.trim()} onClick={()=>command('restore_act',{reason},act.id)}>Return to queue</button>}<button className="danger" disabled={!reason.trim()} onClick={()=>{if(confirm('Void this unrevealed act? Locked scores remain in the audit database. Add a new act for a fresh attempt.'))void command('void_act',{reason},act.id)}}>Void act</button></div><p className="muted spaced">Revealed results cannot be rewritten. A void act retains its original scores in the database and is excluded from results.</p></details>}</div>}

export function EventRecovery({event,accounts,command}:{event:Event;accounts:Account[];command:Command}){return <section className="panel wide"><div className="panel-head"><h2>Registration & reserve judges</h2></div><div className="pad form-stack"><button disabled={event.phase==='ENDED'} onClick={()=>command('registration',{open:!event.registration_open})}>{event.registration_open?'Close':'Open'} performer registration</button><form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(confirm('Replace this panel member? Their existing revealed scores will remain unchanged.'))void command('replace_judge',{old:Number(f.get('old')),new:Number(f.get('new')),reason:f.get('reason')})}}><h3>Replace an unavailable judge</h3><label>Assigned judge<select name="old" required><option value="">Choose assigned judge</option>{event.judges.map(id=><option key={id} value={id}>{accounts.find(a=>a.id===id)?.name||id}</option>)}</select></label><label>Reserve judge<select name="new" required><option value="">Choose reserve judge</option>{accounts.filter(a=>a.role==='judge'&&!a.disabled&&!event.judges.includes(a.id)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Reason<textarea name="reason" required maxLength={300}/></label><p className="muted">A judge who already scored the active act cannot be replaced until that act is completed or voided.</p><button disabled={event.phase==='ENDED'}>Replace panel member</button></form></div></section>}

const questions:Record<string,string[]>={Music:['What first drew you to this piece?','What part of this performance took the most practice?','Which musician would you most like to perform with?','If you changed one thing in this arrangement, what would it be?'],Comedy:['Which observation sparked this set?','Which line changed most during rehearsal?','What surprised you about the audience tonight?','How do you decide when a joke is ready for the stage?'],Dance:['What story does this choreography tell?','Which movement took the most practice?','How did you choose the music?','What would a second version of this routine look like?'],Other:['How did you discover this talent?','What was the hardest part to prepare?','What would you like to try next?','Who encouraged you to perform for the first time?']};
export function HostPrompts({category}:{category:string}){const [index,setIndex]=useState(0);const list=questions[category]||questions.Other;useEffect(()=>setIndex(0),[category]);return <div className="host-prompts"><span className="micro">HOST QUESTION GENERATOR · CURATED</span><p className="spaced">{list[index%list.length]}</p><button onClick={()=>setIndex(i=>i+1)}>Next question</button><small className="spaced">Category-based prompts. No personal or AI-generated claims.</small></div>}
